- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create molecule instance(s)
      docker_container:
        name: instance
        image: ubuntu:24.04
        command: sleep infinity
        state: started
        volumes:
          - /tmp/ansible-student:/tmp/ansible-student:rw
      register: server

    - name: Create minimal instance config
      copy:
        content: |
          # Molecule managed
          instance:
            address: instance
            user: root
            port: 22
        dest: "{{ molecule_instance_config }}"
      when: server is changed