driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:24.04
    command: sleep infinity
    pre_build_image: false
    privileged: false
    volumes:
      - /tmp/ansible-student:/tmp/ansible-student:rw
    tmpfs:
      - /tmp
      - /run
      - /run/lock
provisioner:
  name: ansible
  connection_options:
    ansible_connection: docker
    ansible_user: root
    ansible_become: false
    ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      remote_tmp: /tmp/ansible-student
      ansible_remote_tmp: /tmp/ansible-student
      interpreter_python: auto_silent
  inventory:
    host_vars:
      instance:
        ansible_connection: docker
        ansible_user: root
        ansible_become: false
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    converge: converge.yml
scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra